
spring:
  application:
    name: springboot-sentinel
  redis:
    timeout: 30000
    host: localhost
    port: 6379
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        heartbeat-interval-ms: 500

feign:
  sentinel:
    enabled: true #开启feign的sentinel支持

server:
  port: 8088
