spring:
  redis:
    timeout: 30000
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
    cluster:
      nodes:
      - 192.168.100.133:6662
      - 192.168.100.133:6661
      - 192.168.100.130:6663
      - 192.168.100.130:6664
      - 192.168.100.131:6665
      - 192.168.100.131:6666

