spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/spring_demo

      # 格式：
      # uri: mongodb://用户名:密码@IP地址:端口号/数据库名
      # 例：uri: mongodb://user:123456@127.0.0.1:27017/spring_demo

server:
  port: 8090
  servlet:
    context-path: /
