spring:
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:mybatis/mappings/*.xml
  # 显示开启mybatis二级缓存
  configuration:
    cache-enabled: true

server:
  port: 8095
  servlet:
    context-path: /

logging:
  config: classpath:log4j2.yml
